version: '3.4'

x-common-env-vars: &common-env-vars
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@:localhost:5432
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:@postgres:localhost:5432
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "d6Vefz3G9U_ynXB3cr7y_Ak35tAHkEGAVxuz_B-jzWw="
  AIRFLOW__WEBSERVER__SECRET_KEY: "ml-ops-project_c92c7b"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  ASTRONOMER_ENVIRONMENT: local
  UPBIT_ACCESS_KEY: None
  UPBIT_SECRET_KEY: None
  AWS_ACCESS_KEY_ID: None
  AWS_SECRET_ACCESS_KEY: None
  MLFLOW_TRACKING_URI: http://host.docker.internal:5000
  MLFLOW_S3_ENDPOINT_URL: http://host.docker.internal:9000

  AIRFLOW__EMAIL__EMAIL_BACKEND: 'airflow.utils.email.send_email_smtp'
  AIRFLOW__EMAIL__EMAIL_CONN_ID: smtp_default
  AIRFLOW__SMTP__SMTP_MAIL_FROM: 'email@naver.com'

  AIRFLOW__SMTP__SMTP_HOST: 'smtp.naver.com'
  AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
  AIRFLOW__SMTP__SMTP_SSL: 'False'
  AIRFLOW__SMTP__SMTP_PORT: 587
  AIRFLOW__SMTP__SMTP_USER: 'None'
  AIRFLOW__SMTP__SMTP_PASSWORD: 'None'

networks:
  airflow:
    driver: bridge

volumes:
  airflow_logs:
    driver: local

services:

  scheduler:
    image: ml-ops-project_c92c7b/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow scheduler"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-scheduler"
    environment:
      <<: *common-env-vars
    volumes:
      - /home/ubuntu/MLOps-project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/MLOps-project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/MLOps-project/include:/usr/local/airflow/include:z
      - /home/ubuntu/MLOps-project/tests:/usr/local/airflow/tests:z

      - /home/ubuntu/MLOps-project/airflow_settings.yaml:/usr/local/airflow/airflow_settings.yaml:z


      - airflow_logs:/usr/local/airflow/logs

    extra_hosts:
      - "host.docker.internal:host-gateway"



  webserver:
    image: ml-ops-project_c92c7b/airflow:latest
    command: >
      bash -c 'if [[ -z "$$AIRFLOW__API__AUTH_BACKEND" ]] && [[ $$(pip show -f apache-airflow | grep basic_auth.py) ]];
        then export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth ;
        else export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default ; fi &&
        { airflow users create "$$@" || airflow create_user "$$@" ; } &&
        { airflow sync-perm || airflow sync_perm ;} &&
        airflow webserver' -- -r Admin -u admin -e admin@example.com -f admin -l user -p admin
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-webserver"
    depends_on:
      - scheduler
      # - postgres
    environment: *common-env-vars

    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /home/ubuntu/MLOps-project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/MLOps-project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/MLOps-project/include:/usr/local/airflow/include:z
      - /home/ubuntu/MLOps-project/tests:/usr/local/airflow/tests:z

      - airflow_logs:/usr/local/airflow/logs

    healthcheck:
      test: curl --fail http://webserver:8080/health || exit 1
      interval: 2s
      retries: 15
      start_period: 5s
      timeout: 60s

    extra_hosts:
      - "host.docker.internal:host-gateway"


  triggerer:
    image: ml-ops-project_c92c7b/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow triggerer"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-triggerer"
    environment:
      <<: *common-env-vars
    volumes:
      - /home/ubuntu/MLOps-project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/MLOps-project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/MLOps-project/include:/usr/local/airflow/include:z

      - airflow_logs:/usr/local/airflow/logs

    extra_hosts:
      - "host.docker.internal:host-gateway"
