version: '3.4'

services:
  mlflow-server:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile-mlflow
    container_name: mlflow-server
    ports:
      - ${MLFLOW_TRACKING_PORT}:${MLFLOW_TRACKING_PORT}
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}:${MLFLOW_S3_ENDPOINT_MAIN_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - artifact-store
    command:
      - /bin/sh
      - -c
      - |
        mlflow server \
          --backend-store-uri ${DB_TYPE}://${DB_USER}:${DB_PW}@${MLFLOW_DB_HOST} \
          --default-artifact-root ${ARTIFACT_ROOT} \
          --host ${MLFLOW_SERVER_HOST}

  # artifact-store:
  #   image: minio/minio:RELEASE.2024-04-06T05-26-02Z
  #   container_name: artifact-store
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: None
  #     MINIO_ROOT_PASSWORD: None
  #   command: server /data/minio --console-address :9001
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - /home/ubuntu/model_registry:/data/minio
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
