global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: node
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: api
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        #- host.docker.internal:8000
        - localhost:8000
        # 이 부분 cloud run 주소로 변경해야함
