apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: btc-price-prediction
spec:
  template:
    spec:
      containers:
        - image: asia-northeast3-docker.pkg.dev/chromatic-force-426910-d4/btc-price-prediction-model/latest
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
