{
 "title": "Airflow Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "DAG run state",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  dag_id,\r\n  execution_date,\r\n  state\r\nFROM\r\n  dag_run\r\nORDER BY\r\n  execution_date DESC\r\nLIMIT 30;"
    }
   ]
  },
  {
   "title": "DAG information",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT dag_id,\r\n       owners,\r\n       schedule_interval,\r\n       is_active,\r\n       is_paused,\r\n       timetable_description,\r\n       next_dagrun            \r\n  FROM dag\r\n WHERE dag_id IN ('data_pipeline', 'model_monitoring_pipeline', 'model_training_pipeline');\r\n\r\n  "
    }
   ]
  },
  {
   "title": "DAG running time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  dag_id,\r\n  execution_date,\r\n  EXTRACT(EPOCH FROM (end_date - start_date)) AS duration_seconds\r\nFROM\r\n  dag_run\r\nWHERE\r\n  state = 'success'\r\nORDER BY\r\n  execution_date DESC\r\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "DAG failed rate",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  dag_id,\r\n  COUNT(*) AS total_runs,\r\n  COUNT(*) FILTER (WHERE state = 'failed') AS failed_runs,\r\n  (COUNT(*) FILTER (WHERE state = 'failed')::float / COUNT(*)) * 100 AS failure_rate\r\nFROM\r\n  dag_run\r\nGROUP BY\r\n  dag_id\r\nORDER BY\r\n  failure_rate DESC\r\nLIMIT 50;"
    }
   ]
  },
  { "title": "BTC data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "btc_preprocessed latest 10",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM (\r\n    SELECT *\r\n    FROM btc_preprocessed\r\n    ORDER BY time DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "btc_ohlcv latest 10 ",
   "type": "table",
   "description": "업비트에서 가져온 5분봉 데이터 최근 10개",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM (\r\n    SELECT *\r\n    FROM btc_ohlcv\r\n    ORDER BY time DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY time DESC;"
    }
   ]
  }
 ]
}