{
 "title": "FastAPI Monitoring",
 "time": { "from": "2024-06-28T21:35:42.156Z", "to": "2024-06-28T22:35:42.156Z" },
 "panels": [
  {
   "title": "Successful Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(successful_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    { "expr": "sum(failed_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, rate(request_latency_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(request_latency_seconds_bucket[1m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(histogram_quantile(0.75, rate(request_latency_seconds_bucket[1m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(request_latency_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg(histogram_quantile(0.25, rate(request_latency_seconds_bucket[1m])))",
     "legendFormat": "p25"
    }
   ]
  }
 ]
}