{
 "title": "MLflow Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Production Model INFO",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mv.name AS model_name,\r\n  mv.version,\r\n  to_timestamp(mv.creation_time / 1000) AS creation_time,\r\n  to_timestamp(mv.last_updated_time / 1000) AS last_transition_time,\r\n  mv.current_stage,\r\n  m.key AS metric_name,\r\n  m.value AS metric_value\r\nFROM\r\n  model_versions mv\r\nLEFT JOIN\r\n  metrics m ON mv.run_id = m.run_uuid AND m.key = 'f1_score'\r\nWHERE\r\n  mv.current_stage = 'Production'\r\nORDER BY\r\n  mv.last_updated_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Trained Model f1-score latest 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mv.name AS model_name,\r\n  m.value AS f1_score,\r\n  mv.version,\r\n  mv.current_stage,\r\n  to_timestamp(mv.creation_time / 1000) AS creation_time\r\nFROM\r\n  model_versions mv\r\nLEFT JOIN\r\n  metrics m ON mv.run_id = m.run_uuid AND m.key = 'f1_score'\r\nORDER BY\r\n  mv.creation_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Production and Previous Model f1-score",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH production_models AS (\r\n  SELECT\r\n    name AS model_name,\r\n    version,\r\n    to_timestamp(last_updated_time / 1000) AS production_transition_time,\r\n    run_id\r\n  FROM\r\n    model_versions\r\n  WHERE\r\n    current_stage = 'Production'\r\n),\r\nprevious_models AS (\r\n  SELECT\r\n    name AS model_name,\r\n    version,\r\n    to_timestamp(last_updated_time / 1000) AS previous_transition_time,\r\n    run_id\r\n  FROM\r\n    model_versions\r\n  WHERE\r\n    current_stage != 'Production'\r\n),\r\nprevious_model_f1 AS (\r\n  SELECT\r\n    run_uuid,\r\n    value AS previous_f1_score\r\n  FROM\r\n    metrics\r\n  WHERE\r\n    key = 'f1_score'\r\n),\r\nproduction_model_f1 AS (\r\n  SELECT\r\n    run_uuid,\r\n    value AS production_f1_score\r\n  FROM\r\n    metrics\r\n  WHERE\r\n    key = 'f1_score'\r\n)\r\nSELECT\r\n  p.model_name,\r\n  p.version AS production_version,\r\n  p.production_transition_time,\r\n  prev.version AS previous_version,\r\n  prev.previous_transition_time,\r\n  prev_f1.previous_f1_score,\r\n  prod_f1.production_f1_score\r\nFROM\r\n  production_models p\r\nLEFT JOIN\r\n  previous_models prev ON p.model_name = prev.model_name AND p.production_transition_time > prev.previous_transition_time\r\nLEFT JOIN\r\n  previous_model_f1 prev_f1 ON prev.run_id = prev_f1.run_uuid\r\nLEFT JOIN\r\n  production_model_f1 prod_f1 ON p.run_id = prod_f1.run_uuid\r\nORDER BY\r\n  p.production_transition_time DESC\r\nLIMIT 20;"
    }
   ]
  }
 ]
}