name: Create .env File

on:
  workflow_call:
    inputs:
      SSH_PRIVATE_KEY:
        type: string
        required: true
      SSH_HOST:
        type: string
        required: true
      SSH_USERNAME:
        type: string
        required: true

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env File on Remote Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ inputs.SSH_PRIVATE_KEY }}
          host: ${{ inputs.SSH_HOST }}
          username: ${{ inputs.SSH_USERNAME }}
          script: |
            echo "⭐️ .env 파일 설정 및 업데이트"
            if [ ! -f ".env" ]; then
                touch .env
            else
                echo "✅ .env 파일이 이미 존재합니다."
            fi
            echo "DB_TYPE=${{ vars.DB_TYPE }}" > .env
            echo "ARTIFACT_ROOT=${{ vars.ARTIFACT_ROOT }}" >> .env
            echo "ARTIFACT_MODEL_REGISTRY_PATH=${{ vars.ARTIFACT_MODEL_REGISTRY_PATH }}" >> .env
            echo "ENV=${{ vars.ENV }}" >> .env

            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PW=${{ secrets.DB_PW }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_URL=${{ secrets.MLFLOW_S3_ENDPOINT_URL }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_MAIN_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_MAIN_PORT }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
            echo "MLFLOW_TRACKING_PORT=${{ secrets.MLFLOW_TRACKING_PORT }}" >> .env
            echo "MLFLOW_DB_HOST=${{ secrets.MLFLOW_DB_HOST }}" >> .env
            echo "MLFLOW_TRACKING_URI_LOCAL=${{ secrets.MLFLOW_TRACKING_URI_LOCAL }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_SUB_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_SUB_PORT }}" >> .env
            echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> .env
            echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> .env
            echo "DB_DEFAULT_NAME=${{ secrets.DB_DEFAULT_NAME }}" >> .env
            echo "MLFLOW_SERVER_HOST=${{ secrets.MLFLOW_SERVER_HOST }}" >> .env
            echo "UVICORN_PORT=${{ secrets.UVICORN_PORT }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

            echo "⭐️ 환경 변수 업데이트 완료"
