name: Instance Environment Setup Workflow

on:
  push:
    branches:
      - develop

jobs:
  initialization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initial Server Setup
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            export ANSIBLE_FORCE_COLOR=1
            export DEBIAN_FRONTEND=noninteractive
            if [ ! -f /home/${{ secrets.SSH_USERNAME }}/.setup_done ]; then
              echo "⭐️ Git 설정"
              git config --global user.name "team JATH"
              git config --global user.email "dohk325@gmail.com"

              echo "⭐️ 시스템 업데이트 및 패키지 설치"
              sudo apt update && sudo apt -y upgrade

              echo "⭐️ PostgreSQL 설정"
              sudo sh -c \
                'echo "deb http://apt.postgresql.org/pub/repos/apt \
                  $(lsb_release -cs)-pgdg main" \
                > /etc/apt/sources.list.d/pgdg.list'
              wget --quiet -O - \
                https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
                sudo apt-key add -
              sudo apt-get update && sudo apt-get -y install postgresql-14

              echo "⭐️ 필요한 패키지 설치"
              sudo apt-get -y install \
                apt-transport-https \
                ca-certificates curl \
                gnupg-agent \
                software-properties-common

              echo "⭐️ Docker 설치"
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
                sudo apt-key add -
              sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable"
              sudo apt-get update && sudo apt-get install -y \
                docker-ce \
                docker-ce-cli \
                containerd.io
              sudo usermod -aG docker ${{ secrets.SSH_USERNAME }}
              sudo chmod 666 /var/run/docker.sock
              sudo systemctl restart docker

              echo "⭐️ Docker Compose 설치"
              sudo apt -y install docker-compose

              echo "⭐️ SSH 키 생성 및 GitHub 등록"
              if [ ! -f ~/.ssh/id_rsa ]; then
                ssh-keygen \
                  -t rsa \
                  -b 4096 \
                  -C "dohk325@gmail.com" \
                  -f ~/.ssh/id_rsa \
                  -N ""
              fi
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
              curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                  -X POST \
                  -d "{\"title\":\"workflow-ssh-key\",\"key\":\"$PUBLIC_KEY\"}" \
                  https://api.github.com/user/keys

              echo "⭐️ Miniconda 설치"
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
                -O Miniconda3.sh
              bash Miniconda3.sh -b -p $HOME/miniconda
              echo "export PATH=\"$HOME/miniconda/bin:\$PATH\"" >> ~/.bashrc
              source ~/.bashrc
              source $HOME/miniconda/etc/profile.d/conda.sh
              rm Miniconda3.sh

              echo "⭐️ Conda 환경 생성"
              conda create -n mlops-pipeline python=3.11 -y
              conda create -n fastapi python=3.11 -y

              echo "⭐️ Git 리포지토리 클론 및 환경 설정"
              git clone git@github.com:MLOps-CoinAssistant/MLOps-project.git
              git clone git@github.com:MLOps-CoinAssistant/fastapi.git
              cd MLOps-project
              conda activate mlops-pipeline
              pip install pip==24.0
              pip install mlflow==1.27.0
              pip install poetry
              pip install pre-commit
              pip install yamllint
              sudo apt install -y shellcheck
              conda deactivate

              echo "⭐️ Astronomer 설치"
              curl -sSL install.astronomer.io | sudo bash -s -- v1.25.0
              echo 'n' | astro dev init

              echo "⭐️ restart-airflow.sh 파일 생성 및 권한 설정"
              echo "#!/bin/bash
              astro dev stop && astro dev kill
              export \$(grep -v '^#' .env | xargs)
              astro dev start --compose-file compose.yaml -e .env" > restart-airflow.sh
              sudo chmod 775 restart-airflow.sh

              echo "⭐️ .env 파일 설정"
              # GitHub Secrets에서 환경 변수를 가져와 .env 파일 생성
              touch .env
              echo "DB_TYPE=${{ vars.DB_TYPE }}" > .env
              echo "ARTIFACT_ROOT=${{ vars.ARTIFACT_ROOT }}" >> .env
              echo "ARTIFACT_MODEL_REGISTRY_PATH=${{ vars.ARTIFACT_MODEL_REGISTRY_PATH }}" >> .env
              echo "ENV=${{ vars.ENV }}" >> .env

              echo "DB_USER=${{ secrets.DB_USER }}" >> .env
              echo "DB_PW=${{ secrets.DB_PW }}" >> .env
              echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
              echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
              echo "MLFLOW_S3_ENDPOINT_URL=${{ secrets.MLFLOW_S3_ENDPOINT_URL }}" >> .env
              echo "MLFLOW_S3_ENDPOINT_MAIN_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_MAIN_PORT }}" >> .env
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
              echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
              echo "MLFLOW_TRACKING_PORT=${{ secrets.MLFLOW_TRACKING_PORT }}" >> .env
              echo "MLFLOW_DB_HOST=${{ secrets.MLFLOW_DB_HOST }}" >> .env
              echo "MLFLOW_TRACKING_URI_LOCAL=${{ secrets.MLFLOW_TRACKING_URI_LOCAL }}" >> .env
              echo "MLFLOW_S3_ENDPOINT_SUB_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_SUB_PORT }}" >> .env
              echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> .env
              echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> .env
              echo "DB_DEFAULT_NAME=${{ secrets.DB_DEFAULT_NAME }}" >> .env
              echo "MLFLOW_SERVER_HOST=${{ secrets.MLFLOW_SERVER_HOST }}" >> .env
              echo "UVICORN_PORT=${{ secrets.UVICORN_PORT }}" >> .env
              echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
              echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

              echo "⭐️ Astronomer 개발 서버 초기화"
              astro dev start
              if grep -q "address already in use"; then
                echo "‼️ 포트 5432가 이미 사용 중입니다. Astro 프로세스를 종료합니다."
                pkill astro
                sudo systemctl stop postgresql
                astro dev stop && astro dev kill
              fi

              cd ${{ vars.PROJECT_PATH }}/MLOps-project

              # airflow_settings.yaml 문제 해결
              if [ -d "airflow_settings.yaml" ]; then
                rm -rf airflow_settings.yaml
              fi
              if [ ! -f "airflow_settings.yaml" ]; then
                touch airflow_settings.yaml
              fi

              echo "⭐️ Astronomer 재시작"
              ./restart-airflow.sh

              if [ -d "airflow_settings.yaml" ]; then
                rm -rf airflow_settings.yaml
              fi
              if [ ! -f "airflow_settings.yaml" ]; then
                touch airflow_settings.yaml
              fi

              if ! grep -q "Airflow is starting up!"; then
                echo "⭐️ Astronomer 개발 서버 재시작"
                ./restart-airflow.sh
              fi
              echo "⭐️ 설정 완료"
              touch /home/${{ secrets.SSH_USERNAME }}/.setup_done
            else
              echo "⭐️ Already Initialized"
            fi

  configure_airflow:
    runs-on: ubuntu-latest
    needs: initialization

    steps:
      - name: Configure Airflow Variables and Connections
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "⭐️ Airflow Variables 추가"

            airflow variables set UPBIT_ACCESS_API_KEY "${{ secrets.UPBIT_ACCESS_API_KEY }}"
            airflow variables set UPBIT_SECRET_API_KEY "${{ secrets.UPBIT_SECRET_API_KEY }}"
            airflow variables set OPENAI_API_KEY "${{ secrets.OPENAI_API_KEY }}"

            echo "⭐️ Airflow Connection 추가"
            airflow connections add 'POSTGRES_DEFAULT' \
              --conn-type 'postgres' \
              --conn-host "${{ secrets.DB_HOST }}" \
              --conn-login "${{ secrets.DB_USER }}" \
              --conn-password "${{ secrets.DB_PW }}" \
              --conn-port "${{ secrets.DB_PORT }}" \
              --conn-schema "${{ secrets.DB_USER }}"
            echo "✅ postgres_default 추가 완료"

            airflow connections add 'HYPERPARAMETER_STORE' \
              --conn-type 'postgres' \
              --conn-host "${{ secrets.DB_HOST }}" \
              --conn-login "${{ secrets.DB_USER }}" \
              --conn-password "${{ secrets.DB_PW }}" \
              --conn-port "${{ secrets.DB_PORT }}" \
              --conn-schema "${{ secrets.DB_USER }}"

            echo "⭐️ Airflow 설정 완료"

  deployment:
    runs-on: ubuntu-latest
    needs: initialization

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        # env:
        #   REPOSITORY_NAME: ${{ github.event.repository.name }}
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd
            CURRENT_DIR=$(pwd)
            echo "현재 위치: $(pwd)"

            ENV_FILE_PATH="./.env"
            BACKUP_FILE_PATH="./.env.backup"

            # .env 파일 백업이 없는 경우 백업 파일 생성
            if [ ! -f "$BACKUP_FILE_PATH" ]; then
                echo "백업 파일이 존재하지 않습니다. 초기 백업 파일을 생성합니다."
                cp "$ENV_FILE_PATH" "$BACKUP_FILE_PATH"
                echo "초기 백업 파일 생성 완료."
                exit 0
            fi

            cd $CURRENT_DIR/${{ vars.repository_name }}
            git pull origin develop
            echo "⭐️ 배포 완료"
            echo "DB_TYPE=${{ vars.DB_TYPE }}" > .env
            echo "ARTIFACT_ROOT=${{ vars.ARTIFACT_ROOT }}" >> .env
            echo "ARTIFACT_MODEL_REGISTRY_PATH=${{ vars.ARTIFACT_MODEL_REGISTRY_PATH }}" >> .env
            echo "ENV=${{ vars.ENV }}" >> .env
            echo "dohyung=${{ vars.dohyung }}" >> .env

            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PW=${{ secrets.DB_PW }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_URL=${{ secrets.MLFLOW_S3_ENDPOINT_URL }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_MAIN_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_MAIN_PORT }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
            echo "MLFLOW_TRACKING_PORT=${{ secrets.MLFLOW_TRACKING_PORT }}" >> .env
            echo "MLFLOW_DB_HOST=${{ secrets.MLFLOW_DB_HOST }}" >> .env
            echo "MLFLOW_TRACKING_URI_LOCAL=${{ secrets.MLFLOW_TRACKING_URI_LOCAL }}" >> .env
            echo "MLFLOW_S3_ENDPOINT_SUB_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_SUB_PORT }}" >> .env
            echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> .env
            echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> .env
            echo "DB_DEFAULT_NAME=${{ secrets.DB_DEFAULT_NAME }}" >> .env
            echo "MLFLOW_SERVER_HOST=${{ secrets.MLFLOW_SERVER_HOST }}" >> .env
            echo "UVICORN_PORT=${{ secrets.UVICORN_PORT }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

            echo "⭐️ 환경 변수 업데이트 완료"

            if git diff --name-only HEAD~1 | grep -E 'compose.yaml'; then
              echo "⭐️ compose.yaml 변동 감지됨"
              ./restart-airflow.sh
            else
              # .env 파일과 백업 파일 비교
              if diff "$ENV_FILE_PATH" "$BACKUP_FILE_PATH" > /dev/null; then
                  echo "✅ .env에 변경 사항이 없습니다."
              else
                  echo "✅ .env에 변경 사항이 감지되었습니다!"
                  # 변경 사항을 반영하여 백업 파일 갱신
                  cp "$ENV_FILE_PATH" "$BACKUP_FILE_PATH"

                  echo "✅ Airflow를 재시작합니다..."
                  # Airflow 재시작 스크립트 실행
                  ./restart-airflow.sh
              fi
            fi

            echo "⭐️ Airflow 재시작 완료"
