name: Instance Environment Setup Workflow

on:
  push:
    branches:
      - develop

jobs:
  initialization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initial Server Setup-I
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            export ANSIBLE_FORCE_COLOR=1
            export DEBIAN_FRONTEND=noninteractive
            if [ ! -f /home/${{ secrets.SSH_USERNAME }}/.setup_done ]; then
              echo "⭐️ Git 설정"
              git config --global user.name "team JATH"
              git config --global user.email "dohk325@gmail.com"

              echo "⭐️ 시스템 업데이트 및 패키지 설치"
              sudo apt update && sudo apt -y upgrade

              echo "⭐️ PostgreSQL 설정"
              sudo sh -c \
                'echo "deb http://apt.postgresql.org/pub/repos/apt \
                  $(lsb_release -cs)-pgdg main" \
                > /etc/apt/sources.list.d/pgdg.list'
              wget --quiet -O - \
                https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
                sudo apt-key add -
              sudo apt-get update && sudo apt-get -y install postgresql-14

              echo "⭐️ 필요한 패키지 설치"
              sudo apt-get -y install \
                apt-transport-https \
                ca-certificates curl \
                gnupg-agent \
                software-properties-common

              echo "⭐️ Docker 설치"
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
                sudo apt-key add -
              sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable"
              sudo apt-get update && sudo apt-get install -y \
                docker-ce \
                docker-ce-cli \
                containerd.io
              sudo usermod -aG docker ${{ secrets.SSH_USERNAME }}
              sudo chmod 666 /var/run/docker.sock
              sudo systemctl restart docker

              echo "⭐️ Docker Compose 설치"
              sudo apt -y install docker-compose

              echo "⭐️ SSH 키 생성 및 GitHub 등록"
              if [ ! -f ~/.ssh/id_rsa ]; then
                ssh-keygen \
                  -t rsa \
                  -b 4096 \
                  -C "ubuntu" \
                  -f ~/.ssh/id_rsa \
                  -N ""
              fi
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
              curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                  -X POST \
                  -d "{\"title\":\"workflow-ssh-key\",\"key\":\"$PUBLIC_KEY\"}" \
                  https://api.github.com/user/keys

              echo "⭐️ Miniconda 설치"
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
                -O Miniconda3.sh
              bash Miniconda3.sh -b -p $HOME/miniconda
              echo "export PATH=\"$HOME/miniconda/bin:\$PATH\"" >> ~/.bashrc
              source ~/.bashrc
              source $HOME/miniconda/etc/profile.d/conda.sh
              rm Miniconda3.sh

              echo "⭐️ Conda 환경 생성"
              conda create -n mlops-pipeline python=3.11 -y
              conda create -n fastapi python=3.11 -y

              echo "⭐️ Git 리포지토리 클론 및 환경 설정"
              git clone git@github.com:MLOps-CoinAssistant/${{ vars.REPOSITORY_NAME }}.git
              git clone git@github.com:MLOps-CoinAssistant/fastapi.git
              cd ${{ vars.REPOSITORY_NAME }}
              conda init
              conda activate mlops-pipeline
              pip install pip==24.0
              pip install mlflow==1.27.0
              pip install poetry==1.5.1
              pip install pre-commit==3.3.3
              pip install yamllint==1.32.0
              pip install psycopg2-binary==2.9.9
              pip install sqlalchemy==1.4.52
              pip install boto3==1.26.90
              pip install ipykernel==6.25.0
              sudo apt install -y shellcheck
              pip install "apache-airflow==2.7.2" \
                --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt"
              
              conda deactivate

              echo "⭐️ Astronomer 설치"
              curl -sSL install.astronomer.io | sudo bash -s -- v1.25.0
              echo 'n' | astro dev init

              echo "⭐️ Astronomer 개발 서버 초기화"
              timeout 300 astro dev start || true 
              if netstat -tuln | grep -q ':5432'; then
                echo "‼️ 포트 5432가 이미 사용 중입니다. 프로세스를 종료합니다."
                sudo systemctl stop postgresql || true
                pkill astro || true
                astro dev stop || true
                astro dev kill || true
              fi

              cd ${{ vars.PROJECT_PATH }}/${{ vars.REPOSITORY_NAME }}

              # airflow_settings.yaml 문제 해결
              if [ -d "airflow_settings.yaml" ]; then
                rm -rf airflow_settings.yaml
              fi
              if [ ! -f "airflow_settings.yaml" ]; then
                touch airflow_settings.yaml
              fi
              
              echo "⭐️ 설정 완료"
              touch /home/${{ secrets.SSH_USERNAME }}/.setup_done
            else
              echo "⭐️ Already Initialized"
            fi

  create_env:
    needs: initialization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if .env exists
        id: check_env
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            if [ -f "/home/${{ secrets.SSH_USERNAME }}/MLOps-project/.env" ]; then
              echo "⭐️ .env file already exists"
              exit 0
            else
              echo "⭐️ .env file does not exist"
              exit 1
            fi

      - name: Create .env File
        if: ${{ failure() }}  # 이전 단계가 실패했을 때만 실행 (즉, .env 파일이 없을 때)
        uses: ./.github/actions/create-env
        with:
          PROJECT_PATH: ${{ vars.PROJECT_PATH }}
          REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          DB_TYPE: ${{ vars.DB_TYPE }}
          ARTIFACT_ROOT: ${{ vars.ARTIFACT_ROOT }}
          ARTIFACT_MODEL_REGISTRY_PATH: ${{ vars.ARTIFACT_MODEL_REGISTRY_PATH }}
          ENV: ${{ vars.ENV }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
          MLFLOW_S3_ENDPOINT_MAIN_PORT: ${{ secrets.MLFLOW_S3_ENDPOINT_MAIN_PORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_EXTERNAL_PORT: ${{ secrets.MLFLOW_TRACKING_EXTERNAL_PORT }}
          MLFLOW_TRACKING_INTERNAL_PORT: ${{ secrets.MLFLOW_TRACKING_INTERNAL_PORT }}
          MLFLOW_DB_HOST: ${{ secrets.MLFLOW_DB_HOST }}
          MLFLOW_TRACKING_URI_LOCAL: ${{ secrets.MLFLOW_TRACKING_URI_LOCAL }}
          MLFLOW_S3_ENDPOINT_SUB_PORT: ${{ secrets.MLFLOW_S3_ENDPOINT_SUB_PORT }}
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          DB_DEFAULT_NAME: ${{ secrets.DB_DEFAULT_NAME }}
          MLFLOW_SERVER_HOST: ${{ secrets.MLFLOW_SERVER_HOST }}
          UVICORN_PORT: ${{ secrets.UVICORN_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}

  configure_airflow:
    runs-on: ubuntu-latest
    needs: [create_env]

    steps:
      - name: Configure Airflow Variables and Connections
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "⭐️ Airflow Variables 추가"

            airflow db init
            
            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow variables set UPBIT_ACCESS_API_KEY "${{ secrets.UPBIT_ACCESS_API_KEY }}"
            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow variables set UPBIT_SECRET_API_KEY "${{ secrets.UPBIT_SECRET_API_KEY }}"
            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow variables set OPENAI_API_KEY "${{ secrets.OPENAI_API_KEY }}"
            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow variables set email_addr "${{ secrets.EMAIL_ADDR }}"

            echo "⭐️ Airflow Connection 추가"
            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow connections add 'POSTGRES_DEFAULT' \
              --conn-type 'postgres' \
              --conn-host "${{ secrets.DB_HOST }}" \
              --conn-login "${{ secrets.DB_USER }}" \
              --conn-password "${{ secrets.DB_PW }}" \
              --conn-port "${{ secrets.DB_PORT }}" \
              --conn-schema "${{ secrets.DB_USER }}"
            echo "✅ postgres_default 추가 완료"

            docker-compose -p ml-ops-project_c92c7b -f compose.yaml exec webserver airflow connections add 'HYPERPARAMETER_STORE' \
              --conn-type 'postgres' \
              --conn-host "${{ secrets.DB_HOST }}" \
              --conn-login "${{ secrets.DB_USER }}" \
              --conn-password "${{ secrets.DB_PW }}" \
              --conn-port "${{ secrets.DB_PORT }}" \
              --conn-schema "${{ secrets.DB_USER }}"

            echo "⭐️ Airflow 설정 완료"

  deployment:
    runs-on: ubuntu-latest
    needs: [initialization, create_env]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application-I
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd
            CURRENT_DIR=$(pwd)
            echo "현재 위치: $(pwd)"

            ENV_FILE_PATH="$CURRENT_DIR/${{ vars.repository_name }}/.env"
            BACKUP_FILE_PATH="$CURRENT_DIR/${{ vars.repository_name }}/.env.backup"

            # .env 파일 백업이 없는 경우 백업 파일 생성
            if [ ! -f "$BACKUP_FILE_PATH" ]; then
                echo "✅ .env 초기 백업 파일 생성"
                cp "$ENV_FILE_PATH" "$BACKUP_FILE_PATH"
                echo "초기 백업 파일 생성 완료."
                exit 0
            fi

            cd $CURRENT_DIR/${{ vars.repository_name }}
            git pull origin develop
            echo "⭐️ 배포 완료"

            if git diff --name-only HEAD~1 | grep -E 'compose.yaml'; then
              echo "⭐️ compose.yaml 변동 감지됨"
              ./restart-services.sh
            fi

            # .env 파일과 백업 파일 비교
            if diff "$ENV_FILE_PATH" "$BACKUP_FILE_PATH" > /dev/null; then
                echo "✅ .env에 변경 사항이 없습니다."
            else
                echo "✅ .env에 변경 사항이 감지되었습니다!"
                # 변경 사항을 반영하여 백업 파일 갱신
                cp "$ENV_FILE_PATH" "$BACKUP_FILE_PATH"

                echo "✅ Airflow를 재시작합니다..."
                # Airflow 재시작 스크립트 실행
                ./restart-services.sh
            fi

            echo "⭐️ Airflow 재시작 완료"
