name: Instance Environment Setup Workflow

on:
  push:
    branches:
      - develop

jobs:
  initialization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initial Server Setup
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            if [ ! -f /home/${{ secrets.SSH_USERNAME }}/.setup_done ]; then
              echo "⭐️ Git 설정"
              git config --global user.name "team JATH"
              git config --global user.email "dohk325@gmail.com"

              echo "⭐️ 시스템 업데이트 및 패키지 설치"
              sudo apt update && sudo apt -y upgrade

              echo "⭐️ PostgreSQL 설정"
              sudo sh -c \
                'echo "deb http://apt.postgresql.org/pub/repos/apt \
                  $(lsb_release -cs)-pgdg main" \
                > /etc/apt/sources.list.d/pgdg.list'
              wget --quiet -O - \
                https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
                sudo apt-key add -
              sudo apt-get update && sudo apt-get -y install postgresql-14

              echo "⭐️ 필요한 패키지 설치"
              sudo apt-get -y install \
                apt-transport-https \
                ca-certificates curl \
                gnupg-agent \
                software-properties-common

              echo "⭐️ Docker 설치"
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
                sudo apt-key add -
              sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable"
              sudo apt-get update && sudo apt-get install -y \
                docker-ce \
                docker-ce-cli \
                containerd.io
              sudo usermod -aG docker ${{ secrets.SSH_USERNAME }}
              sudo chmod 666 /var/run/docker.sock
              sudo systemctl restart docker

              echo "⭐️ Docker Compose 설치"
              sudo apt -y install docker-compose

              echo "⭐️ SSH 키 생성 및 GitHub 등록"
              if [ ! -f ~/.ssh/id_rsa ]; then
                ssh-keygen \
                  -t rsa \
                  -b 4096 \
                  -C "dohk325@gmail.com" \
                  -f ~/.ssh/id_rsa \
                  -N ""
              fi
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
              curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                  -X POST \
                  -d "{\"title\":\"workflow-ssh-key\",\"key\":\"$PUBLIC_KEY\"}" \
                  https://api.github.com/user/keys

              echo "⭐️ Miniconda 설치"
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
                -O Miniconda3.sh
              bash Miniconda3.sh -b -p $HOME/miniconda
              echo "export PATH=\"$HOME/miniconda/bin:\$PATH\"" >> ~/.bashrc
              source ~/.bashrc
              source $HOME/miniconda/etc/profile.d/conda.sh

              echo "⭐️ Conda 환경 생성"
              conda create -n mlops-pipeline python=3.11 -y
              conda create -n fastapi python=3.11 -y

              echo "⭐️ Git 리포지토리 클론 및 환경 설정"
              git clone git@github.com:MLOps-CoinAssistant/MLOps-project.git
              git clone git@github.com:MLOps-CoinAssistant/fastapi.git
              cd MLOps-project
              conda activate mlops-pipeline
              pip install pip==24.0
              pip install mlflow==1.27.0
              pip install poetry
              pip install pre-commit
              pip install yamllint
              sudo apt install -y shellcheck
              conda deactivate

              echo "⭐️ Astronomer 설치"
              curl -sSL install.astronomer.io | sudo bash -s -- v1.25.0
              echo 'n' | astro dev init

              echo "⭐️ .env 파일 설정"
              # GitHub Secrets에서 환경 변수를 가져와 .env 파일 생성
              touch .env
              echo "DB_TYPE=${{ vars.DB_TYPE }}" > .env
              echo "DB_USER=${{ secrets.DB_USER }}" >> .env
              echo "DB_PW=${{ secrets.DB_PW }}" >> .env
              echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
              echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
              echo "MLFLOW_S3_ENDPOINT_URL=${{ secrets.MLFLOW_S3_ENDPOINT_URL }}" >> .env
              echo "MLFLOW_S3_ENDPOINT_MAIN_PORT=${{ secrets.MLFLOW_S3_ENDPOINT_MAIN_PORT }}" >> .env
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
              echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
              echo "MLFLOW_TRACKING_PORT=${{ secrets.MLFLOW_TRACKING_PORT }}" >> .env

              echo "⭐️ Astronomer 개발 서버 초기화"
              astro dev start
              if grep -q "address already in use" astro_error.log; then
                echo "‼️ 포트 5432가 이미 사용 중입니다. Astro 프로세스를 종료합니다."
                pkill astro
                sudo systemctl stop postgresql
                astro dev stop && astro dev kill
              fi

              echo "⭐️ airflow plugins 폴더 생성 및 권한 변경"
              if [ ! -d "plugins" ]; then
                mkdir plugins
              fi
              sudo chown ubuntu plugins
              sudo chgrp ubuntu plugins

              echo "⭐️ Astronomer 개발 서버 시작:1"
              export $(grep -v '^#' .env | xargs)
              astro dev start --compose-file compose.yaml -e .env

              if grep -q "airflow_settings.yaml: is a directory"; then
                  rm -rf ~/MLOps-project/airflow_settings.yaml
                  touch ~/MLOps-project/airflow_settings.yaml
              fi

              if ! grep -q "Airflow is starting up!"; then
                echo "⭐️ Astronomer 개발 서버 시작"
                export $(grep -v '^#' .env | xargs)
                astro dev start --compose-file compose.yaml -e .env

            fi
  deployment:
    runs-on: ubuntu-latest
    needs: initialization

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        # env:
        #   REPOSITORY_NAME: ${{ github.event.repository.name }}
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd
            CURRENT_DIR=$(pwd)
            echo "현재 위치: $(pwd)"

            cd $CURRENT_DIR/${{ vars.repository_name }}
            git pull origin develop
            echo "⭐️ 배포 완료"
            # 추가적인 배포 명령어들
